# Default values for nginx-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2
image: nginx
orgLabel: payroll
regions:
  - ohio
  - newyork
  - ontario
  - london
  - singapore
  - mumbai