apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  {{- if .Values.orgLabel }}
  labels:
    org: {{ .Values.orgLabel }}
  {{- else if eq .Values.orgLabel "hr" }}
   labels:
    org: human resource
  {{- end }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: hello-world  